version: '2.0'
services:

  tiddlywiki:
    image: dosyoyas/tiddlywiki-arm:latest
    container_name: tiddlywiki-arm
    environment:
        - USERNAME=user
        - PASSWORD=wiki
        - NODE_MEM=256
    volumes:
        - ./.tiddlywiki/:/var/lib/tiddlywiki/
    ports:
        - 8080:8080
